spring:
  # Выполняем schema.sql и data.sql при каждом старте
  sql:
    init:
      mode: always
  datasource:
    # Данные для подключения к БД, БД хранится в файле
    url: jdbc:h2:file:./db/filmorate;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    # Консоль H2 для просмотра БД в браузере
    console:
      enabled: true
      path: /h2

logging:
  file:
    # Дублирование логирования в файл
    name: ./logs/filmorate.log
  level:
    root: INFO
    # Логирование HTTP-запросов
    org.springframework.web: WARN
    # Логирование системной информации при инициализации и запуске сервиса
    org.springframework.boot: WARN
    # Logbook (HTTP-запросы/ответы)
    org.zalando.logbook: TRACE
    # Все классы приложения Filmorate
    ru.yandex.practicum.filmorate: INFO